site_name: iolanta
site_url: https://iolanta.tech
repo_url: https://github.com/iolanta-tech/iolanta
edit_uri: edit/master/docs/
repo_name: iolanta-tech/iolanta
copyright: Copyright © 2026 iolanta.tech

exclude_docs: |
  superpowers/
  **/AGENTS.md

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Howto:
      - ... | glob=howto/**
  - Reference:
      - reference/index.md
      - Ontologies:
          - Iolanta:
              - Facet.md
              - matches.md
              - is-preferred-over.md
              - icon.md
              - outputs.md
              - when-no-facet-found.md
              - has-sub-graph.md
              - visualizes.md
              - reference/iolanta/OutputDatatype.md
              - reference/iolanta/SPARQLText.md
              - reference/ontology/index.md
          - RDF: reference/rdf.md
          - RDFS: reference/rdfs.md
          - OWL: reference/owl.md
      - Tools:
          - reference/cli.md
          - reference/render-template-macros-and-variables.md
      - Datatypes:
          - datatypes/fallback-title.md
          - datatypes/jsonl.md
          - datatypes/title.md
          - datatypes/mermaid.md
          - datatypes/mkdocs-material.md
  - Blog:
      - ... | glob=blog/**
  - Plugins:
      - ... | glob=plugins/**
      - ... | glob=mermaid/**
      - ... | glob=roadmap/**

plugins:
  - search
  - awesome-pages
  - blogging:
      dirs:
        - blog
      features:
        tags: {}
      time_format: '%d %b %Y'  # The format used to display the time
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
  - mkdocs-typer2:
      pretty: true
      engine: native
  - macros:
      on_error_fail: true

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - content.code.annotate
    - content.action.edit
    - content.code.copy
