graph LR
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  https___schema_org_Tool(schema:Tool)
  click https___schema_org_Tool "https://schema.org/Tool"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  https___schema_org_SoftwareApplication(schema:SoftwareApplication)
  click https___schema_org_SoftwareApplication "https://schema.org/SoftwareApplication"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  https___github_com_iolanta-tech_python-yaml-ld(https://github.com/iolanta-tech/python-yaml-ld)
  click https___github_com_iolanta-tech_python-yaml-ld "https://github.com/iolanta-tech/python-yaml-ld"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  26a46af64453c0142f52af06842a4442_b0(YAML-LD Processing)
  26a46af64453c0142f52af06842a4442_b0(YAML-LD Processing)
  Literal-3addc00bc26321d7a9e9c66398eda0ff[[Core functionality for processing YAML-LD documents and converting them to/from JSON-LD and RDF formats]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-8b722a8de4ffe6c2039aeb68f988d4a0[[JSON-LD compaction functionality]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-2f20d730cdf6bd2c94ec036a714a712a[[JSON-LD expansion functionality]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-0c305d4f5b5d0006d9890b66785ad6c8[[JSON-LD framing functionality]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-ab089ca45630b043ce17009824b95e3e[[Wrapper around digitalbazaar/pyld library]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-8a21e7de4a6a959ed1d572d8355475c3[[OS Independent]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-c0f97697d9f1c1b5df09a4d8cd01d4f8[[YAML-LD]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-f8fc300aba1a62521aa0838d84bf0e13[[RDF serialization and deserialization]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-95ff019f720bc520215da8497fe5388d[[JSON-LD flattening functionality]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  https___github_com_iolanta-tech_python-yaml-ld_issues(https://github.com/iolanta-tech/python-yaml-ld/issues)
  click https___github_com_iolanta-tech_python-yaml-ld_issues "https://github.com/iolanta-tech/python-yaml-ld/issues"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-f19f44deac55e6235440595421c1050b[[https://orcid.org/0009-0001-8740-4213]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-a7f5f35426b927411fc9231b56382173[[Python]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-2be52caa263703568b4549b289a5d1ad[[yaml-ld is a Python package that provides functionality for working with YAML-LD documents, which are YAML representations of JSON-LD data. It serves as a convenient wrapper around the digitalbazaar/pyld library, enabling developers to work with Linked Data in YAML format while maintaining compatibility with the JSON-LD specification.]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-cce86c220fbc6693ae48f216761d99ab[[Linked Data]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-671ca9055beeeae16403fde04d79b1c7[[YAML-LD document parsing and transformation]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-3492865fce4f7111821efdcf4dd149e1[[Command-line tool]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-5d99cdc6288533ac58bb6a751b8a07fa[[https://www.wikidata.org/entity/Q28865]]
  26a46af64453c0142f52af06842a4442_b0(YAML-LD Processing)
  https___schema_org_Thing(Thing)
  click https___schema_org_Thing "https://schema.org/Thing"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-2e30b03b439120176763cedca47f7d84[[JSON-LD]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  https___opensource_org_licenses_MIT(https://opensource.org/licenses/MIT)
  click https___opensource_org_licenses_MIT "https://opensource.org/licenses/MIT"
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-103b850abb89c034ccc2a2d2e6756fe3[[Semantic Web]]
  https___pypi_org_project_yaml-ld(yaml-ld)
  click https___pypi_org_project_yaml-ld "https://pypi.org/project/yaml-ld/"
  Literal-bd356d7542feae70dfc82ff346894b07[[A Python implementation for handling YAML-LD documents, serving as a wrapper on top of digitalbazaar/pyld library for JSON-LD processing.]]
  https___pypi_org_project_yaml-ld --- 3d3735f688acf0fee70551b90bb7708c(["applicationCategory"])--> https___schema_org_Tool
  click 3d3735f688acf0fee70551b90bb7708c "https://schema.org/applicationCategory"
  class 3d3735f688acf0fee70551b90bb7708c predicate
  https___pypi_org_project_yaml-ld --- 3afcf410e860fd1e1654601456b571c3(["type"])--> https___schema_org_SoftwareApplication
  click 3afcf410e860fd1e1654601456b571c3 "https://www.w3.org/1999/02/22-rdf-syntax-ns#type"
  class 3afcf410e860fd1e1654601456b571c3 predicate
  https___pypi_org_project_yaml-ld --- e1e4b0c1dfd87be934a943cb67e69109(["codeRepository"])--> https___github_com_iolanta-tech_python-yaml-ld
  click e1e4b0c1dfd87be934a943cb67e69109 "https://schema.org/codeRepository"
  class e1e4b0c1dfd87be934a943cb67e69109 predicate
  https___pypi_org_project_yaml-ld --- 2fd88efd7b750964247bfb4abaeee1f6(["mainEntity"])--> 26a46af64453c0142f52af06842a4442_b0
  click 2fd88efd7b750964247bfb4abaeee1f6 "https://schema.org/mainEntity"
  class 2fd88efd7b750964247bfb4abaeee1f6 predicate
  26a46af64453c0142f52af06842a4442_b0 --- 477e2c69799ad8caa2d2f4b13cc537c1(["description"])--> Literal-3addc00bc26321d7a9e9c66398eda0ff
  click 477e2c69799ad8caa2d2f4b13cc537c1 "https://schema.org/description"
  class 477e2c69799ad8caa2d2f4b13cc537c1 predicate
  https___pypi_org_project_yaml-ld --- c6c356abe135e29fb296a643cea3fad2(["featureList"])--> Literal-8b722a8de4ffe6c2039aeb68f988d4a0
  click c6c356abe135e29fb296a643cea3fad2 "https://schema.org/featureList"
  class c6c356abe135e29fb296a643cea3fad2 predicate
  https___pypi_org_project_yaml-ld --- 70cc9a357b77f37ae3a61dad9c3afb75(["featureList"])--> Literal-2f20d730cdf6bd2c94ec036a714a712a
  click 70cc9a357b77f37ae3a61dad9c3afb75 "https://schema.org/featureList"
  class 70cc9a357b77f37ae3a61dad9c3afb75 predicate
  https___pypi_org_project_yaml-ld --- 2e19f42d7dee6c61ddf8403bad2fa0f8(["featureList"])--> Literal-0c305d4f5b5d0006d9890b66785ad6c8
  click 2e19f42d7dee6c61ddf8403bad2fa0f8 "https://schema.org/featureList"
  class 2e19f42d7dee6c61ddf8403bad2fa0f8 predicate
  https___pypi_org_project_yaml-ld --- 7e52713b40294c4230a5a35116f6d67d(["featureList"])--> Literal-ab089ca45630b043ce17009824b95e3e
  click 7e52713b40294c4230a5a35116f6d67d "https://schema.org/featureList"
  class 7e52713b40294c4230a5a35116f6d67d predicate
  https___pypi_org_project_yaml-ld --- 98edc231651aef0ea26ba099a1490faf(["operatingSystem"])--> Literal-8a21e7de4a6a959ed1d572d8355475c3
  click 98edc231651aef0ea26ba099a1490faf "https://schema.org/operatingSystem"
  class 98edc231651aef0ea26ba099a1490faf predicate
  https___pypi_org_project_yaml-ld --- 452610d9e8b24bacccfd6ace1b1f06ae(["Subject"])--> Literal-c0f97697d9f1c1b5df09a4d8cd01d4f8
  click 452610d9e8b24bacccfd6ace1b1f06ae "https://purl.org/dc/terms/subject"
  class 452610d9e8b24bacccfd6ace1b1f06ae predicate
  https___pypi_org_project_yaml-ld --- 55fe22cee280a3db49aaaa166c595b7e(["downloadUrl"])--> https___pypi_org_project_yaml-ld
  click 55fe22cee280a3db49aaaa166c595b7e "https://schema.org/downloadUrl"
  class 55fe22cee280a3db49aaaa166c595b7e predicate
  https___pypi_org_project_yaml-ld --- df91d4376f2b6d79d4fb9fdc2f445b96(["featureList"])--> Literal-f8fc300aba1a62521aa0838d84bf0e13
  click df91d4376f2b6d79d4fb9fdc2f445b96 "https://schema.org/featureList"
  class df91d4376f2b6d79d4fb9fdc2f445b96 predicate
  https___pypi_org_project_yaml-ld --- f04405243a115f63e956f5361479c1c6(["featureList"])--> Literal-95ff019f720bc520215da8497fe5388d
  click f04405243a115f63e956f5361479c1c6 "https://schema.org/featureList"
  class f04405243a115f63e956f5361479c1c6 predicate
  https___pypi_org_project_yaml-ld --- 9e6ab0db3bd719ffa13b24ec57772b83(["schema:issueTracker"])--> https___github_com_iolanta-tech_python-yaml-ld_issues
  click 9e6ab0db3bd719ffa13b24ec57772b83 "https://schema.org/issueTracker"
  class 9e6ab0db3bd719ffa13b24ec57772b83 predicate
  https___pypi_org_project_yaml-ld --- 3d41abdacbed2ac3cb941f4dbb757887(["author"])--> Literal-f19f44deac55e6235440595421c1050b
  click 3d41abdacbed2ac3cb941f4dbb757887 "https://schema.org/author"
  class 3d41abdacbed2ac3cb941f4dbb757887 predicate
  https___pypi_org_project_yaml-ld --- 4246fb3cff388dcf06ec8693d7eabdaf(["Subject"])--> Literal-a7f5f35426b927411fc9231b56382173
  click 4246fb3cff388dcf06ec8693d7eabdaf "https://purl.org/dc/terms/subject"
  class 4246fb3cff388dcf06ec8693d7eabdaf predicate
  https___pypi_org_project_yaml-ld --- f94001700a42eb8eb487f47e50566977(["comment"])--> Literal-2be52caa263703568b4549b289a5d1ad
  click f94001700a42eb8eb487f47e50566977 "https://www.w3.org/2000/01/rdf-schema#comment"
  class f94001700a42eb8eb487f47e50566977 predicate
  https___pypi_org_project_yaml-ld --- 75cf7223e437091b90241f7017dcab61(["Subject"])--> Literal-cce86c220fbc6693ae48f216761d99ab
  click 75cf7223e437091b90241f7017dcab61 "https://purl.org/dc/terms/subject"
  class 75cf7223e437091b90241f7017dcab61 predicate
  https___pypi_org_project_yaml-ld --- 20b5b2d86a327e57770c3d36b0a92197(["featureList"])--> Literal-671ca9055beeeae16403fde04d79b1c7
  click 20b5b2d86a327e57770c3d36b0a92197 "https://schema.org/featureList"
  class 20b5b2d86a327e57770c3d36b0a92197 predicate
  https___pypi_org_project_yaml-ld --- 9790792905632cb956b108ed6e2afa9e(["applicationSubCategory"])--> Literal-3492865fce4f7111821efdcf4dd149e1
  click 9790792905632cb956b108ed6e2afa9e "https://schema.org/applicationSubCategory"
  class 9790792905632cb956b108ed6e2afa9e predicate
  https___pypi_org_project_yaml-ld --- 2d21bb6a29bd236895a419be10f122b3(["programmingLanguage"])--> Literal-5d99cdc6288533ac58bb6a751b8a07fa
  click 2d21bb6a29bd236895a419be10f122b3 "https://schema.org/programmingLanguage"
  class 2d21bb6a29bd236895a419be10f122b3 predicate
  26a46af64453c0142f52af06842a4442_b0 --- 85656765045e7ecc1acf43fc14cfa08e(["type"])--> https___schema_org_Thing
  click 85656765045e7ecc1acf43fc14cfa08e "https://www.w3.org/1999/02/22-rdf-syntax-ns#type"
  class 85656765045e7ecc1acf43fc14cfa08e predicate
  https___pypi_org_project_yaml-ld --- ec80568cc6ac1a8414bdc35dbe7897f8(["Subject"])--> Literal-2e30b03b439120176763cedca47f7d84
  click ec80568cc6ac1a8414bdc35dbe7897f8 "https://purl.org/dc/terms/subject"
  class ec80568cc6ac1a8414bdc35dbe7897f8 predicate
  https___pypi_org_project_yaml-ld --- b802dfd9f10afb37deab653bc7197532(["license"])--> https___opensource_org_licenses_MIT
  click b802dfd9f10afb37deab653bc7197532 "https://schema.org/license"
  class b802dfd9f10afb37deab653bc7197532 predicate
  https___pypi_org_project_yaml-ld --- a479b2b40bb3c528074adb61055589cb(["Subject"])--> Literal-103b850abb89c034ccc2a2d2e6756fe3
  click a479b2b40bb3c528074adb61055589cb "https://purl.org/dc/terms/subject"
  class a479b2b40bb3c528074adb61055589cb predicate
  https___pypi_org_project_yaml-ld --- f02d77ab716694e5418a7ca7a14e146d(["description"])--> Literal-bd356d7542feae70dfc82ff346894b07
  click f02d77ab716694e5418a7ca7a14e146d "https://schema.org/description"
  class f02d77ab716694e5418a7ca7a14e146d predicate
  classDef predicate fill:none,stroke:none,stroke-width:0px;
