graph LR
  https___dbpedia_org_resource_2309_Mr__Spock("2309 Mr. Spock")
  click https___dbpedia_org_resource_2309_Mr__Spock "https://dbpedia.org/resource/2309_Mr._Spock"
  https___schema_org_Thing("Thing")
  click https___schema_org_Thing "https://schema.org/Thing"
  https___dbpedia_org_resource_2309_Mr__Spock("2309 Mr. Spock")
  click https___dbpedia_org_resource_2309_Mr__Spock "https://dbpedia.org/resource/2309_Mr._Spock"
  https___dbpedia_org_resource_Spock("Spock")
  click https___dbpedia_org_resource_Spock "https://dbpedia.org/resource/Spock"
  https___dbpedia_org_resource_2309_Mr__Spock("2309 Mr. Spock")
  click https___dbpedia_org_resource_2309_Mr__Spock "https://dbpedia.org/resource/2309_Mr._Spock"
  Literal-fb3b883d09405ded0240ac25e05f3e9d[["Asteroid 2309, named after Mr. Spock from Star Trek"]]
  https___dbpedia_org_resource_2309_Mr__Spock --- bba306a162268892860702ccfe86546a(["type"])--> https___schema_org_Thing
  click bba306a162268892860702ccfe86546a "https://www.w3.org/1999/02/22-rdf-syntax-ns#type"
  class bba306a162268892860702ccfe86546a predicate
  https___dbpedia_org_resource_2309_Mr__Spock --- d6579ddc6337d85d3453e6b552b8e3c9(["named after"])--> https___dbpedia_org_resource_Spock
  click d6579ddc6337d85d3453e6b552b8e3c9 "https://www.wikidata.org/entity/P138"
  class d6579ddc6337d85d3453e6b552b8e3c9 predicate
  https___dbpedia_org_resource_2309_Mr__Spock --- 0366bb6eff71464e6d38ce17c6ffda0d(["description"])--> Literal-fb3b883d09405ded0240ac25e05f3e9d
  click 0366bb6eff71464e6d38ce17c6ffda0d "https://schema.org/description"
  class 0366bb6eff71464e6d38ce17c6ffda0d predicate
  classDef predicate fill:none,stroke:none,stroke-width:0px;
