graph LR
  subgraph subgraph_790d6d3641d92df45eaa829c3d9273df["w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/assertion"]
    direction LR
      https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1("Rhysling")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/_n92643406680d4021ba7c46f7b878d4c2b1"
    Literal-75043864482d691a40119f68b0d57c6c[["Noisy"]]
    https___dbpedia_org_resource_Rhysling__crater_("Rhysling (crater)")
    click https___dbpedia_org_resource_Rhysling__crater_ "https://dbpedia.org/resource/Rhysling_(crater)"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1("Rhysling")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/_n92643406680d4021ba7c46f7b878d4c2b1"
    https___dbpedia_org_resource_The_Green_Hills_of_Earth("The Green Hills of Earth")
    click https___dbpedia_org_resource_The_Green_Hills_of_Earth "https://dbpedia.org/resource/The_Green_Hills_of_Earth"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1("Rhysling")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/_n92643406680d4021ba7c46f7b878d4c2b1"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1("Rhysling")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/_n92643406680d4021ba7c46f7b878d4c2b1"
    Literal-41ffd32a77c7e389468f1b2f2209cc6f[["Fictional character from Robert A. Heinlein's short story "The Green Hills of Earth""]]
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1("Rhysling")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/_n92643406680d4021ba7c46f7b878d4c2b1"
    https___schema_org_Person("Person")
    click https___schema_org_Person "https://schema.org/Person"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 --- 07654879cff877978338b53d7bab17d5(["alternateName"])--> Literal-75043864482d691a40119f68b0d57c6c
    click 07654879cff877978338b53d7bab17d5 "https://schema.org/alternateName"
    class 07654879cff877978338b53d7bab17d5 predicate
    https___dbpedia_org_resource_Rhysling__crater_ --- 246b435e561739ab98f77e47c4a02992(["named after"])--> https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1
    click 246b435e561739ab98f77e47c4a02992 "https://www.wikidata.org/entity/P138"
    class 246b435e561739ab98f77e47c4a02992 predicate
    https___dbpedia_org_resource_The_Green_Hills_of_Earth --- 93e454406129284f699d20ae3f547c28(["character"])--> https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1
    click 93e454406129284f699d20ae3f547c28 "https://schema.org/character"
    class 93e454406129284f699d20ae3f547c28 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 --- aac3b71c9a5f0026e75bc8343498c4d2(["description"])--> Literal-41ffd32a77c7e389468f1b2f2209cc6f
    click aac3b71c9a5f0026e75bc8343498c4d2 "https://schema.org/description"
    class aac3b71c9a5f0026e75bc8343498c4d2 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk__n92643406680d4021ba7c46f7b878d4c2b1 --- 9269bcdd2680d588b6fcf618d73adbfd(["type"])--> https___schema_org_Person
    click 9269bcdd2680d588b6fcf618d73adbfd "https://www.w3.org/1999/02/22-rdf-syntax-ns#type"
    class 9269bcdd2680d588b6fcf618d73adbfd predicate
  end
  subgraph subgraph_7cc3b8b042ba27cb778b537f57f48fab["w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/provenance"]
    direction LR
      https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/provenance#w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/assertion")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/provenance#https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/assertion"
    Literal-5374cbcbc1fc9e1d6291b1dacc6fbf7a[["2025-09-27T18:01:16.079850"]]
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/provenance#w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/assertion")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/provenance#https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/assertion"
    https___dbpedia_org_resource_Rhysling__crater_("Rhysling (crater)")
    click https___dbpedia_org_resource_Rhysling__crater_ "https://dbpedia.org/resource/Rhysling_(crater)"
    https___dbpedia_org_resource_Rhysling__crater_("Rhysling (crater)")
    click https___dbpedia_org_resource_Rhysling__crater_ "https://dbpedia.org/resource/Rhysling_(crater)"
    Literal-5374cbcbc1fc9e1d6291b1dacc6fbf7a[["2025-09-27T18:01:16.079850"]]
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion --- ef6fe95e1c2ad2e2581d51136b7bbfd9(["generatedAtTime"])--> Literal-5374cbcbc1fc9e1d6291b1dacc6fbf7a
    click ef6fe95e1c2ad2e2581d51136b7bbfd9 "https://www.w3.org/ns/prov#generatedAtTime"
    class ef6fe95e1c2ad2e2581d51136b7bbfd9 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion --- 145e4bed8f2ce8c964cada3034d0fdac(["wasDerivedFrom"])--> https___dbpedia_org_resource_Rhysling__crater_
    click 145e4bed8f2ce8c964cada3034d0fdac "https://www.w3.org/ns/prov#wasDerivedFrom"
    class 145e4bed8f2ce8c964cada3034d0fdac predicate
    subgraph_790d6d3641d92df45eaa829c3d9273df --- bc6d3024ddebe13178935276ca6391d4(["wasDerivedFrom"])--> https___dbpedia_org_resource_Rhysling__crater_
    click bc6d3024ddebe13178935276ca6391d4 "https://www.w3.org/ns/prov#wasDerivedFrom"
    class bc6d3024ddebe13178935276ca6391d4 predicate
    subgraph_790d6d3641d92df45eaa829c3d9273df --- 827c71c9e50d15a3ea74ed9ef1b6daef(["generatedAtTime"])--> Literal-5374cbcbc1fc9e1d6291b1dacc6fbf7a
    click 827c71c9e50d15a3ea74ed9ef1b6daef "https://www.w3.org/ns/prov#generatedAtTime"
    class 827c71c9e50d15a3ea74ed9ef1b6daef predicate
  end
  subgraph subgraph_c348249ae9dc0d4e618b126856f23d2a["w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/pubinfo"]
    direction LR
      https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig"
    Literal-445d0434ad7b42aff5bab616ebb41970[["RSA"]]
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig"
    Literal-16f1e3af24f6bc3dff2d73611b1e5192[["eMreE1RimNP6Q25XRg5HQw6RQ3hb7oeWVcG8a3sb+tUawaWVMkSf9xHBfKQhtg7KTvog4ciaDV8XigfUx5TrFo+/lYhb0pmXmwQWTHiGkmwGYv+yauGBCAL0eibiB4TVGyL7fkDhEU25zvxSuYw1QZxGdd4MGaV3yxtj+Zfp8C+LXoFxSmJAzJ+NCzDgoYtuGFlxTLDwcQgWHFNN4LnIlXLdLhMz4c+v9h9PbP3WyKOJzF9wFa/yRQJmH+EjOi71Q40wIYB5MTuPDN8pxSExf8Fm4XRH/hWEROTBoDPBF3keMNEgq1n0hatNEC29EcewR1jdSjSaZFhSjlIlNy4JWw=="]]
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig"
    Literal-b8d3010139fae5b6f31b08e9bf814089[["MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA79G1aksiLFmT7Lco5+qLImUeO0Dfli7k1R76QYoVtuMV0w4fQdv9oLXGGpLZ7U25pH7j2UHKk2R/4LSwoZCeMvIdbSfLpxTOSjD9scUiJWjwPHLH7/e946ENlhi52GANdYMGa+FxEQGR9HiHIoYn99AYUcYqkJ7qeOgXMJdkL6vZACdzeepAGajgC/jiscJuxmBtWCoqqi0GnG0AIXq14E9VgscSMLZ63i30mKDWwSZF1FFBLUHDSV+CLaFKBfjsGzVVU85jlYSWJ2E0FJ+w0cRnNB3B2bmPI7miy7okzQIqagEHop4bbaPmbgG5uMX2lMgb6RX0oU5hqU4B8FwHUwIDAQAB"]]
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig"
    https___orcid_org_0009-0001-8740-4213("Anatoly Scherbakov")
    click https___orcid_org_0009-0001-8740-4213 "https://orcid.org/0009-0001-8740-4213"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    Literal-5374cbcbc1fc9e1d6291b1dacc6fbf7a[["2025-09-27T18:01:16.079850"]]
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/sig"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___orcid_org_0009-0001-8740-4213("Anatoly Scherbakov")
    click https___orcid_org_0009-0001-8740-4213 "https://orcid.org/0009-0001-8740-4213"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig --- 3553da7281d27eb0b81a1b9e840779d9(["purl.org/nanopub/x/hasAlgorithm"])--> Literal-445d0434ad7b42aff5bab616ebb41970
    click 3553da7281d27eb0b81a1b9e840779d9 "https://purl.org/nanopub/x/hasAlgorithm"
    class 3553da7281d27eb0b81a1b9e840779d9 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig --- 8c241887e1b8e11ea26ab84ec61505dd(["purl.org/nanopub/x/hasSignature"])--> Literal-16f1e3af24f6bc3dff2d73611b1e5192
    click 8c241887e1b8e11ea26ab84ec61505dd "https://purl.org/nanopub/x/hasSignature"
    class 8c241887e1b8e11ea26ab84ec61505dd predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig --- 98f3618bc696afe4b178370bbf2fd246(["purl.org/nanopub/x/hasPublicKey"])--> Literal-b8d3010139fae5b6f31b08e9bf814089
    click 98f3618bc696afe4b178370bbf2fd246 "https://purl.org/nanopub/x/hasPublicKey"
    class 98f3618bc696afe4b178370bbf2fd246 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig --- 7d3d825e06956ebb2b3e89facfbef608(["purl.org/nanopub/x/signedBy"])--> https___orcid_org_0009-0001-8740-4213
    click 7d3d825e06956ebb2b3e89facfbef608 "https://purl.org/nanopub/x/signedBy"
    class 7d3d825e06956ebb2b3e89facfbef608 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- 128c659b0893ec1626717c6dbc427411(["generatedAtTime"])--> Literal-5374cbcbc1fc9e1d6291b1dacc6fbf7a
    click 128c659b0893ec1626717c6dbc427411 "https://www.w3.org/ns/prov#generatedAtTime"
    class 128c659b0893ec1626717c6dbc427411 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_sig --- 1693bdc2322d95c10da1207d00d962f8(["purl.org/nanopub/x/hasSignatureTarget"])--> https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk
    click 1693bdc2322d95c10da1207d00d962f8 "https://purl.org/nanopub/x/hasSignatureTarget"
    class 1693bdc2322d95c10da1207d00d962f8 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- 6a1e47fc7d65f3b004ce357768744f1b(["wasAttributedTo"])--> https___orcid_org_0009-0001-8740-4213
    click 6a1e47fc7d65f3b004ce357768744f1b "https://www.w3.org/ns/prov#wasAttributedTo"
    class 6a1e47fc7d65f3b004ce357768744f1b predicate
  end
  subgraph subgraph_3495805fe81bd3367a9d4465b617f5ed["w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/Head"]
    direction LR
      https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/Head#w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/assertion")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/Head#https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/assertion"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_pubinfo("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/Head#w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/pubinfo")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_pubinfo "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/Head#https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/pubinfo"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/Head#w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/provenance")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/Head#https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk/provenance"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk("w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk")
    click https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk "https://w3id.org/np/RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk"
    https___www_nanopub_org_nschema_Nanopublication("Nanopublication")
    click https___www_nanopub_org_nschema_Nanopublication "https://www.nanopub.org/nschema#Nanopublication"
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- 316c8d72a7b2f7c1e53dfad46683f807(["nanopub.org/nschema#hasPublicationInfo"])--> subgraph_c348249ae9dc0d4e618b126856f23d2a
    click 316c8d72a7b2f7c1e53dfad46683f807 "https://www.nanopub.org/nschema#hasPublicationInfo"
    class 316c8d72a7b2f7c1e53dfad46683f807 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- d3933b0af31f59aaaaa5eace7f36b854(["nanopub.org/nschema#hasAssertion"])--> https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_assertion
    click d3933b0af31f59aaaaa5eace7f36b854 "https://www.nanopub.org/nschema#hasAssertion"
    class d3933b0af31f59aaaaa5eace7f36b854 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- 3e3460399b758536c484083248d46e88(["nanopub.org/nschema#hasPublicationInfo"])--> https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_pubinfo
    click 3e3460399b758536c484083248d46e88 "https://www.nanopub.org/nschema#hasPublicationInfo"
    class 3e3460399b758536c484083248d46e88 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- 9ef8ef71008493b01985e43c624bdee3(["nanopub.org/nschema#hasProvenance"])--> subgraph_7cc3b8b042ba27cb778b537f57f48fab
    click 9ef8ef71008493b01985e43c624bdee3 "https://www.nanopub.org/nschema#hasProvenance"
    class 9ef8ef71008493b01985e43c624bdee3 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- db2be051158966f8f536aad8522aac1f(["nanopub.org/nschema#hasProvenance"])--> https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_Head_https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk_provenance
    click db2be051158966f8f536aad8522aac1f "https://www.nanopub.org/nschema#hasProvenance"
    class db2be051158966f8f536aad8522aac1f predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- 5cf1ebb2d03634234dced0c36c089a17(["nanopub.org/nschema#hasAssertion"])--> subgraph_790d6d3641d92df45eaa829c3d9273df
    click 5cf1ebb2d03634234dced0c36c089a17 "https://www.nanopub.org/nschema#hasAssertion"
    class 5cf1ebb2d03634234dced0c36c089a17 predicate
    https___w3id_org_np_RAJbt59EaFWRYrTt4bPm95v9egxrMpZ41ZWViz51O12rk --- a3a6812cc0866fa17a28ca9668e9a2e6(["type"])--> https___www_nanopub_org_nschema_Nanopublication
    click a3a6812cc0866fa17a28ca9668e9a2e6 "https://www.w3.org/1999/02/22-rdf-syntax-ns#type"
    class a3a6812cc0866fa17a28ca9668e9a2e6 predicate
  end
  classDef predicate fill:none,stroke:none,stroke-width:0px;
