graph LR
  B98f04eb24ae2("⬜ _:f4540b989ab9907722cd2dc73d6e52a0_b0")
  Literal_8014343f4e7d[["📅 2026-06-21"]]
  https___example_org_alice("example.org/alice")
  click https___example_org_alice "https://example.org/alice"
  Be0de211c8297("⬜ _:50220cb55346e704efeede96b308275c_b0")
  Literal_0dd877826005[["Ally"]]
  Literal_8b1a9953c461[["🇺🇸 Hello"]]
  Literal_a1d0c6e83f02[["🔢 42"]]
  Literal_b326b5062b2f[["✅ true"]]
  Literal_64489c85dc2f[["Alice"]]
  B98f04eb24ae2 --- Edge_09e4a699329c(["example.org/born"])--> Literal_8014343f4e7d
  click Edge_09e4a699329c "https://example.org/born"
  https___example_org_alice --- Edge_53ae90511ba8(["example.org/profile"])--> Be0de211c8297
  click Edge_53ae90511ba8 "https://example.org/profile"
  B98f04eb24ae2 --- Edge_1e22f0ed311b(["example.org/nickname"])--> Literal_0dd877826005
  click Edge_1e22f0ed311b "https://example.org/nickname"
  Be0de211c8297 --- Edge_b5f478f05bc8(["example.org/note"])--> Literal_8b1a9953c461
  click Edge_b5f478f05bc8 "https://example.org/note"
  B98f04eb24ae2 --- Edge_173b3b615086(["example.org/score"])--> Literal_a1d0c6e83f02
  click Edge_173b3b615086 "https://example.org/score"
  B98f04eb24ae2 --- Edge_779e3096eef2(["example.org/active"])--> Literal_b326b5062b2f
  click Edge_779e3096eef2 "https://example.org/active"
  Be0de211c8297 --- Edge_01cfd6ff8bc0(["example.org/score"])--> Literal_a1d0c6e83f02
  click Edge_01cfd6ff8bc0 "https://example.org/score"
  B98f04eb24ae2 --- Edge_0dac97bbcc7c(["example.org/note"])--> Literal_8b1a9953c461
  click Edge_0dac97bbcc7c "https://example.org/note"
  Be0de211c8297 --- Edge_a78767aca651(["example.org/active"])--> Literal_b326b5062b2f
  click Edge_a78767aca651 "https://example.org/active"
  https___example_org_alice --- Edge_237f32a1b424(["example.org/profile"])--> B98f04eb24ae2
  click Edge_237f32a1b424 "https://example.org/profile"
  https___example_org_alice --- Edge_cf62963bbcd2(["schema.org/name"])--> Literal_64489c85dc2f
  click Edge_cf62963bbcd2 "https://schema.org/name"
  Be0de211c8297 --- Edge_2d6160344ca5(["example.org/nickname"])--> Literal_0dd877826005
  click Edge_2d6160344ca5 "https://example.org/nickname"
  Be0de211c8297 --- Edge_1014c6e33ff4(["example.org/born"])--> Literal_8014343f4e7d
  click Edge_1014c6e33ff4 "https://example.org/born"
  classDef predicate fill:#1f2233,stroke:transparent,color:#f8fafc,stroke-width:0px;
  classDef hidden fill:transparent,stroke:transparent,color:transparent,stroke-width:0px;
  classDef nanopubdot fill:#0f172a,stroke:#0f172a,color:transparent,stroke-width:2px;
  classDef transparent fill:transparent,stroke:transparent,color:transparent,stroke-width:0px;
  
