PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX local: <https://iolanta.tech/apps/iolanta-rdfs/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX iolanta-rdfs: <http://localhost:8000/iolanta-rdfs.n3>

CONSTRUCT {
  # ?subject ?predicate ?object .
  ?g rdfs:contains ?subject .
}

FROM NAMED rdfs:
FROM NAMED iolanta-rdfs:

WHERE {
  GRAPH ?g {
    ?subject ?predicate ?object .
  }
}
