PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX local: <https://iolanta.tech/apps/iolanta-rdfs/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>


CONSTRUCT {
  ?ontology rdfs:label ?ontology_label .
  ?ontology local:meta owl:Ontology .

  # TODO This should be in iolanta-rdfs app ontology, actually
  owl:Ontology rdfs:label "Ontology" .

} WHERE {
  ?ontology a owl:Ontology .
  ?ontology dc:title ?ontology_label .

  ?entity rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> .
  ?entity rdf:type rdfs:Class .
}
