PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX local: <https://iolanta.tech/apps/iolanta-rdfs/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

CONSTRUCT {
  ?section local:blocks ?entity .

  ?entity
    rdfs:label ?entity_label ;
    rdfs:comment ?entity_comment ;
    a ?entity_superclass .

} WHERE {
  ?section
    a local:Category .

  ?entity
    rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> ;
    rdfs:label ?entity_label ;
    local:category ?section ;
    rdfs:comment ?entity_comment ;
    a ?entity_superclass .

  OPTIONAL {
    GRAPH local: {
      ?entity rdfs:label ?preferred_entity_in_section_label .
    }
  }

  GRAPH rdfs: {
    ?entity rdfs:label ?default_entity_in_section_label .
  }

  BIND(
    IF(
      BOUND(?preferred_entity_in_section_label),
      ?preferred_entity_in_section_label,
      ?default_entity_in_section_label
    ) AS ?entity_label
  )
}
