PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX local: <https://iolanta.tech/apps/iolanta-rdfs/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>


CONSTRUCT {
  ?ontology rdfs:label ?ontology_label .
  ?ontology local:meta owl:Ontology .

  # TODO This should be in iolanta-rdfs app ontology or in OWL ontology, actually
  owl:Ontology rdfs:label "Ontology" .

  # Categories list
  ?ontology local:categories ?category .
  ?category rdfs:label ?category_label .
  ?category local:parent ?parent_category .

  # And the blocks
  ?ontology local:blocks ?entity .
  ?entity rdfs:label ?entity_label .
  ?entity local:category ?entity_category .
  ?entity rdfs:isSubclassOf ?super_class .

} WHERE {
  ?ontology a owl:Ontology .
  ?ontology dc:title ?ontology_label .

  ?entity rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> .
  ?entity rdf:type rdfs:Class .
  ?entity rdfs:label ?entity_label .
  ?entity local:category ?entity_category .

  # Fetch categories
  ?category a local:Category .
  ?category rdfs:label ?category_label .
  OPTIONAL {
    ?category local:parent ?parent_category .
  }
}
