PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX local: <https://iolanta.tech/apps/iolanta-rdfs/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

CONSTRUCT {
  ?rdfs rdfs:label ?rdfs_label .
  ?rdfs local:meta owl:Ontology .

  # TODO This should be in iolanta-rdfs app ontology or in OWL ontology, actually
  owl:Ontology rdfs:label "Ontology" .

  # Top level sections
  ?rdfs local:sections ?section .
  ?section rdfs:label ?section_label .

  # Blocks in top-level sections
  ?section local:blocks ?entity_in_section .
  ?entity_in_section rdfs:label ?entity_in_section_label .

  # Subsections
  ?section local:sections ?subsection .
  ?subsection rdfs:label ?subsection_label .

  # Blocks in subsections
  ?subsection local:blocks ?entity_in_subsection .
  ?entity_in_subsection rdfs:label ?entity_in_subsection_label .

} WHERE {
  # RDFS ontology properties
  ?rdfs a owl:Ontology .
  ?rdfs dc:title ?rdfs_label .

  # Top level sections
  ?section a local:Category .
  ?section rdfs:label ?section_label .
  FILTER NOT EXISTS { ?section local:parent ?anything } .

  # Subsections, if any
  OPTIONAL {
    ?subsection a local:Category .
    ?subsection rdfs:label ?subsection_label .
    ?subsection local:parent ?section .

    # If subsection exists, it must have entities
    ?entity_in_subsection rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> .
    ?entity_in_subsection rdfs:label ?entity_in_subsection_label .
    ?entity_in_subsection local:category ?subsection .
  }

  # Entities in top-level section, if any
  OPTIONAL {
    ?entity_in_section rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> .
    ?entity_in_section rdfs:label ?entity_in_section_label .
    ?entity_in_section local:category ?section .
  }
}
