graph LR
  https___dbpedia_org_resource_2026_Armenian_parliamentary_election("2026 Armenian parliamentary election")
  click https___dbpedia_org_resource_2026_Armenian_parliamentary_election "https://dbpedia.org/resource/2026_Armenian_parliamentary_election"
  https___www_wikidata_org_entity_Q327333("wikidata.org/entity/Q327333")
  click https___www_wikidata_org_entity_Q327333 "https://www.wikidata.org/entity/Q327333"
  https___dbpedia_org_resource_2026_Armenian_parliamentary_election("2026 Armenian parliamentary election")
  click https___dbpedia_org_resource_2026_Armenian_parliamentary_election "https://dbpedia.org/resource/2026_Armenian_parliamentary_election"
  https___www_wikidata_org_entity_Q399("wikidata.org/entity/Q399")
  click https___www_wikidata_org_entity_Q399 "https://www.wikidata.org/entity/Q399"
  https___dbpedia_org_resource_2026_Armenian_parliamentary_election("2026 Armenian parliamentary election")
  click https___dbpedia_org_resource_2026_Armenian_parliamentary_election "https://dbpedia.org/resource/2026_Armenian_parliamentary_election"
  Literal-4f44311cabca43f74f8b0946aacdb026[["2026-06-07"]]
  https___dbpedia_org_resource_2026_Armenian_parliamentary_election --- 8ef2cef7e0174d248c80583e06635f73(["organizer"])--> https___www_wikidata_org_entity_Q327333
  click 8ef2cef7e0174d248c80583e06635f73 "https://schema.org/organizer"
  class 8ef2cef7e0174d248c80583e06635f73 predicate
  https___dbpedia_org_resource_2026_Armenian_parliamentary_election --- 800d9d0c8f543457d0e9c3ab2ad6b6d5(["location"])--> https___www_wikidata_org_entity_Q399
  click 800d9d0c8f543457d0e9c3ab2ad6b6d5 "https://schema.org/location"
  class 800d9d0c8f543457d0e9c3ab2ad6b6d5 predicate
  https___dbpedia_org_resource_2026_Armenian_parliamentary_election --- 936fe9463f3e68a88f32ed19508e0164(["startDate"])--> Literal-4f44311cabca43f74f8b0946aacdb026
  click 936fe9463f3e68a88f32ed19508e0164 "https://schema.org/startDate"
  class 936fe9463f3e68a88f32ed19508e0164 predicate
  classDef predicate fill:none,stroke:none,stroke-width:0px;