graph LR
  http___dbpedia_org_resource_John_Lennon("John Lennon")
  click http___dbpedia_org_resource_John_Lennon "http://dbpedia.org/resource/John_Lennon"
  http___dbpedia_org_resource_Yoko_Ono("Yoko Ono")
  click http___dbpedia_org_resource_Yoko_Ono "http://dbpedia.org/resource/Yoko_Ono"
  http___dbpedia_org_resource_John_Lennon("John Lennon")
  click http___dbpedia_org_resource_John_Lennon "http://dbpedia.org/resource/John_Lennon"
  Literal-4649fa93775b9ab0c7a5e1bd15b6744a[["📅 1940-10-09"]]
  http___dbpedia_org_resource_John_Lennon("John Lennon")
  click http___dbpedia_org_resource_John_Lennon "http://dbpedia.org/resource/John_Lennon"
  http___dbpedia_org_resource_Cynthia_Lennon("Cynthia Lennon")
  click http___dbpedia_org_resource_Cynthia_Lennon "http://dbpedia.org/resource/Cynthia_Lennon"
  http___dbpedia_org_resource_John_Lennon --- 203e23da021cfaec8fe3608f1809cc89(["spouse"])--> http___dbpedia_org_resource_Yoko_Ono
  click 203e23da021cfaec8fe3608f1809cc89 "http://schema.org/spouse"
  class 203e23da021cfaec8fe3608f1809cc89 predicate
  http___dbpedia_org_resource_John_Lennon --- 1759f753de49b9a729174a0162121fbc(["birthDate"])--> Literal-4649fa93775b9ab0c7a5e1bd15b6744a
  click 1759f753de49b9a729174a0162121fbc "http://schema.org/birthDate"
  class 1759f753de49b9a729174a0162121fbc predicate
  http___dbpedia_org_resource_John_Lennon --- 5467d103f69601bbafb5c89daa6ba9e2(["spouse"])--> http___dbpedia_org_resource_Cynthia_Lennon
  click 5467d103f69601bbafb5c89daa6ba9e2 "http://schema.org/spouse"
  class 5467d103f69601bbafb5c89daa6ba9e2 predicate
  classDef predicate fill:#1f2233,stroke:transparent,color:#f8fafc,stroke-width:0px;
  classDef hidden fill:transparent,stroke:transparent,color:transparent,stroke-width:0px;
  classDef label fill:transparent,stroke:transparent,color:#e5e7eb,stroke-width:0px;
  classDef nanopubdot fill:#0f172a,stroke:#0f172a,color:transparent,stroke-width:2px;
  classDef transparent fill:transparent,stroke:transparent,color:transparent,stroke-width:0px;
  
