prefix wikibase: <http://wikiba.se/ontology#>

INSERT {
  GRAPH <local:wikibase-entity-property> {
    ?statement rdfs:label ?label .
  }
}
WHERE {
    ?statement
        ?prop_statement ?entity ;
        a wikibase:Statement .

    ?prop_statement a owl:ObjectProperty .
    ?entity a wikibase:Item .

    ?entity rdfs:label ?label .
}
