PREFIX vs: <https://www.w3.org/2003/06/sw-vocab-status/ns#>

PREFIX iolanta: <https://iolanta.tech/>

SELECT DISTINCT ?term ?group ?comment ?status ?icon WHERE {
    ?term rdfs:isDefinedBy $iri .
    FILTER (?term != $iri)

    OPTIONAL {
        ?term rdf:type ?group .
        $iri vann:termGroup ?group .
    }

    OPTIONAL {
        ?term rdfs:comment ?comment .
    }

    OPTIONAL {
        ?term vs:term_status ?status .
    }

    OPTIONAL {
        ?term iolanta:icon ?icon .
        FILTER(isLiteral(?icon))
    }
}
ORDER BY (!BOUND(?group)) ?group ?term COALESCE(STR(?icon), "")
